using System;
using System.Collections.Generic;
using System.Text;

namespace Chinook.DataLoader
{
	/// <summary>
	/// A <see cref="IDataLoaderRequest"/> is a request to load a <see cref="IDataLoader"/>.
	/// </summary>
	public interface IDataLoaderRequest
	{
		/// <summary>
		/// The sequence Id of this request, generated by the <see cref="IDataLoader"/>.
		/// </summary>
		/// <remarks>
		/// This is a 0 based sequence with increments of 1, meaning that 0 is the first request of the <see cref="IDataLoader"/>, 1 is the second, and so on.
		/// </remarks>
		public int SequenceId { get; }

		/// <summary>
		/// Gets the trigger that originated the request.
		/// </summary>
		IDataLoaderTrigger SourceTrigger { get; }

		/// <summary>
		/// Gets the metadata contained in the request.
		/// </summary>
		/// <remarks>
		/// Items added are kept for the lifetime of the <see cref="IDataLoader"/>.
		/// </remarks>
		IDataLoaderContext Context { get; }
	}
}
