using System;
using System.Collections.Generic;
using System.Text;

namespace Chinook.DataLoader
{
	/// <summary>
	/// This is a default implementation of <see cref="IDataLoaderRequest"/>.
	/// </summary>
	public class DataLoaderRequest : IDataLoaderRequest
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DataLoaderRequest"/> class.
		/// </summary>
		/// <param name="sequenceId">The sequence Id of this request.</param>
		/// <param name="sourceTrigger"><see cref="IDataLoaderTrigger"/></param>
		/// <param name="context"><see cref="IDataLoaderContext"/></param>
		public DataLoaderRequest(int sequenceId, IDataLoaderTrigger sourceTrigger, IDataLoaderContext context = null)
		{
			SequenceId = sequenceId;
			SourceTrigger = sourceTrigger ?? throw new ArgumentNullException(nameof(sourceTrigger));
			Context = context ?? new DataLoaderContext();
		}

		/// <summary>
		/// The sequence Id of this request, generated by the <see cref="IDataLoader"/>.
		/// </summary>
		public int SequenceId { get; }

		/// <inheritdoc />
		public IDataLoaderTrigger SourceTrigger { get; }

		/// <inheritdoc />
		public IDataLoaderContext Context { get; }

		/// <inheritdoc />
		public override string ToString()
		{
			return "Request #" + SequenceId;
		}
	}
}
